# version: "3.8"

volumes:
  wp_data:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/jacha/data/wordpress
  db_data:
    driver: local
    name: mariadb
    driver_opts:
      type: none
      o: bind
      device: /home/jacha/data/mariadb
      
networks:
  inception:
    name: inception
    driver: bridge

secrets:
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_password:
    file: ../secrets/db_password.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt
  wp_user_password:
    file: ../secrets/wp_user_password.txt

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    secrets:
      - db_root_password
      - db_password
    environment:
      - DB_USER=${DB_USER}
      - DB_NAME=${DB_NAME}
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - .env
    networks:
      - inception
    restart: unless-stopped

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    secrets:
      - db_password
      - wp_admin_password
      - wp_user_password
    environment:
      - DOMAIN_NAME=jacha.42.fr
      - WP_TITLE=jacha WordPress
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_NAME=${DB_NAME}
      - WP_ADMIN_USER=${WP_ADMIN_USER}
      - WP_ADMIN_EMAIL=${WP_ADMIN_EMAIL}
      - WP_USER=${WP_USER}
      - WP_USER_EMAIL=${WP_USER_EMAIL}
    volumes:
      - wp_data:/var/www/html
    env_file:
      - .env
    networks:
      - inception
    depends_on:
      - mariadb
    restart: always

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    environment:
      - DB_USER=${DB_USER}
      - DB_NAME=${DB_NAME}
    volumes:
      - wp_data:/var/www/html
    env_file:
      - .env
    networks:
      - inception
    ports:
      - "443:443"
    depends_on:
      - wordpress
    restart: unless-stopped
