// Error codes for API responses
// Frontend will translate these codes using l10n

const ErrorCodes = {
    // Auth errors
    AUTH: {
        MISSING_REQUIRED_FIELDS: 'MISSING_REQUIRED_FIELDS',
        INVALID_USERNAME: 'INVALID_USERNAME',
        INVALID_EMAIL: 'INVALID_EMAIL',
        INVALID_DISPLAY_NAME: 'INVALID_DISPLAY_NAME',
        PASSWORD_TOO_SHORT: 'PASSWORD_TOO_SHORT',
        USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
        REGISTRATION_FAILED: 'REGISTRATION_FAILED',
        MISSING_CREDENTIALS: 'MISSING_CREDENTIALS',
        INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
        INVALID_2FA_CODE: 'INVALID_2FA_CODE',
        LOGIN_FAILED: 'LOGIN_FAILED',
        LOGOUT_FAILED: 'LOGOUT_FAILED',
        '2FA_SETUP_FAILED': '2FA_SETUP_FAILED',
        TOKEN_REQUIRED: 'TOKEN_REQUIRED',
        '2FA_NOT_SETUP': '2FA_NOT_SETUP',
        INVALID_TOKEN: 'INVALID_TOKEN',
        '2FA_VERIFICATION_FAILED': '2FA_VERIFICATION_FAILED',
        PASSWORD_REQUIRED: 'PASSWORD_REQUIRED',
        INVALID_PASSWORD: 'INVALID_PASSWORD',
        '2FA_DISABLE_FAILED': '2FA_DISABLE_FAILED',
        ALREADY_LOGGED_IN: 'ALREADY_LOGGED_IN',
    },

    // User errors
    USERS: {
        USER_NOT_FOUND: 'USER_NOT_FOUND',
        FETCH_USER_FAILED: 'FETCH_USER_FAILED',
        QUERY_TOO_SHORT: 'QUERY_TOO_SHORT',
        SEARCH_FAILED: 'SEARCH_FAILED',
        INVALID_FIELD: 'INVALID_FIELD',
        EMAIL_IN_USE: 'EMAIL_IN_USE',
        NO_UPDATES_PROVIDED: 'NO_UPDATES_PROVIDED',
        UPDATE_FAILED: 'UPDATE_FAILED',
        NO_FILE_UPLOADED: 'NO_FILE_UPLOADED',
        INVALID_FILE_TYPE: 'INVALID_FILE_TYPE',
        FILE_TOO_LARGE: 'FILE_TOO_LARGE',
        UPLOAD_AVATAR_FAILED: 'UPLOAD_AVATAR_FAILED',
        NO_AVATAR_TO_DELETE: 'NO_AVATAR_TO_DELETE',
        DELETE_AVATAR_FAILED: 'DELETE_AVATAR_FAILED',
        FETCH_STATS_FAILED: 'FETCH_STATS_FAILED',
    },

    // Game errors
    GAMES: {
        CREATE_GAME_FAILED: 'CREATE_GAME_FAILED',
        GAME_NOT_FOUND: 'GAME_NOT_FOUND',
        FETCH_GAME_FAILED: 'FETCH_GAME_FAILED',
        FETCH_MATCH_HISTORY_FAILED: 'FETCH_MATCH_HISTORY_FAILED',
        FETCH_RECENT_GAMES_FAILED: 'FETCH_RECENT_GAMES_FAILED',
    },

    // Tournament errors
    TOURNAMENTS: {
        NAME_AND_MAX_PLAYERS_REQUIRED: 'NAME_AND_MAX_PLAYERS_REQUIRED',
        INVALID_NAME: 'INVALID_NAME',
        INVALID_MAX_PLAYERS: 'INVALID_MAX_PLAYERS',
        CREATE_TOURNAMENT_FAILED: 'CREATE_TOURNAMENT_FAILED',
        TOURNAMENT_NOT_FOUND: 'TOURNAMENT_NOT_FOUND',
        FETCH_TOURNAMENT_FAILED: 'FETCH_TOURNAMENT_FAILED',
        ALIAS_TOO_LONG: 'ALIAS_TOO_LONG',
        TOURNAMENT_NOT_FOUND_OR_STARTED: 'TOURNAMENT_NOT_FOUND_OR_STARTED',
        TOURNAMENT_FULL: 'TOURNAMENT_FULL',
        ALREADY_JOINED: 'ALREADY_JOINED',
        JOIN_TOURNAMENT_FAILED: 'JOIN_TOURNAMENT_FAILED',
        ALIAS_REQUIRED: 'ALIAS_REQUIRED',
        INVALID_ALIAS_LENGTH: 'INVALID_ALIAS_LENGTH',
        NOT_CREATOR: 'NOT_CREATOR',
        TOURNAMENT_ALREADY_STARTED: 'TOURNAMENT_ALREADY_STARTED',
        NOT_ENOUGH_PLAYERS: 'NOT_ENOUGH_PLAYERS',
        NOT_ENOUGH_PLAYERS_FOR_MAX: 'NOT_ENOUGH_PLAYERS_FOR_MAX',
        START_TOURNAMENT_FAILED: 'START_TOURNAMENT_FAILED',
        FETCH_TOURNAMENTS_FAILED: 'FETCH_TOURNAMENTS_FAILED',
    },

    // Friend errors
    FRIENDS: {
        FETCH_FRIENDS_FAILED: 'FETCH_FRIENDS_FAILED',
        FRIEND_ID_REQUIRED: 'FRIEND_ID_REQUIRED',
        CANNOT_ADD_SELF: 'CANNOT_ADD_SELF',
        USER_NOT_FOUND: 'USER_NOT_FOUND',
        FRIEND_REQUEST_PENDING: 'FRIEND_REQUEST_PENDING',
        ALREADY_FRIENDS: 'ALREADY_FRIENDS',
        CANNOT_SEND_REQUEST: 'CANNOT_SEND_REQUEST',
        SEND_FRIEND_REQUEST_FAILED: 'SEND_FRIEND_REQUEST_FAILED',
        FRIEND_REQUEST_NOT_FOUND: 'FRIEND_REQUEST_NOT_FOUND',
        ACCEPT_FRIEND_REQUEST_FAILED: 'ACCEPT_FRIEND_REQUEST_FAILED',
        FRIENDSHIP_NOT_FOUND: 'FRIENDSHIP_NOT_FOUND',
        REMOVE_FRIENDSHIP_FAILED: 'REMOVE_FRIENDSHIP_FAILED',
        FETCH_FRIEND_REQUESTS_FAILED: 'FETCH_FRIEND_REQUESTS_FAILED',
        FETCH_ONLINE_FRIENDS_FAILED: 'FETCH_ONLINE_FRIENDS_FAILED',
    },

    // Middleware errors
    MIDDLEWARE: {
        ACCESS_TOKEN_REQUIRED: 'ACCESS_TOKEN_REQUIRED',
        INVALID_OR_EXPIRED_TOKEN: 'INVALID_OR_EXPIRED_TOKEN',
        SESSION_EXPIRED: 'SESSION_EXPIRED',
    },

    // Generic errors
    GENERIC: {
        INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
        NOT_ALLOWED_BY_CORS: 'NOT_ALLOWED_BY_CORS',
    }
};

module.exports = ErrorCodes;
