server {
    listen 443 ssl http2;
    server_name jacha.42.fr _;

    access_log /dev/stdout;
    error_log  /dev/stderr warn;

    # 자체 서명 인증서 경로
    ssl_certificate     /etc/nginx/ssl/selfsigned.crt;
    ssl_certificate_key /etc/nginx/ssl/selfsigned.key;

    # 과제 요구: TLSv1.2 또는 TLSv1.3만
    ssl_protocols TLSv1.2 TLSv1.3;

    root  /var/www/wordpress;
    index index.php index.html;

    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    # PHP-FPM (WordPress 컨테이너가 0.0.0.0:9000으로 리슨)
    location ~ \.php$ {
        include /etc/nginx/fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_index index.php;
        fastcgi_read_timeout 120s;
        fastcgi_pass wordpress:9000;
    }
}