FROM debian:bookworm

RUN apt-get update && apt-get install -y \
	netcat-openbsd \
	php8.2-fpm \
	php8.2-mysql \
	php8.2-curl \
	php8.2-gd \
	php8.2-xml \
	php8.2-mbstring \
	php8.2-zip \
	php8.2-cli \
	curl \
	ca-certificates \
	tar \
	less \
	default-mysql-client \
	&& rm -rf /var/lib/apt/lists/*

RUN curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar \
    && chmod +x wp-cli.phar \
    && mv wp-cli.phar /usr/local/bin/wp

COPY conf/www.conf /etc/php/8.2/fpm/pool.d/www.conf
COPY tools/setup_wp.sh /

RUN chmod +x /setup_wp.sh

WORKDIR /var/www/html
EXPOSE 9000

ENTRYPOINT ["/setup_wp.sh"]
